version: '3'

services:
  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile-dist
      args:
        #Pasamos argumentos para el dockerfile
        php_version: ${PHP_VERSION}
    container_name: ${WEB_WERVER_NAME}
    ports:
      - "${PHP_PORT}:80"
    restart: unless-stopped