version: '3'

services:
  web:
    build:
      context: ./web-server
      args:
        #Pasamos argumentos para el dockerfile
        php_version: ${PHP_VERSION}
    container_name: ${WEB_WERVER_NAME}
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./web-server/www:/var/www/html
    restart: unless-stopped